CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "link" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    code VARCHAR(10) NOT NULL UNIQUE,
    original_url VARCHAR (2048) NOT NULL,
    redirect_limit INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "link_counter" (
    id BIGINT PRIMARY KEY,
    counter BIGINT NOT NULL
);

INSERT INTO link_counter (id, counter)
SELECT 1, 0
WHERE NOT EXISTS (SELECT 1 FROM link_counter WHERE id = 1);